worker_processes 1;

events {
    worker_connections  512;
}

http {
    include /etc/nginx/mime.types;

    proxy_buffering         on;
    proxy_buffer_size       256k;
    proxy_buffers           4   256k;

    ### === AI SERVICES ===
    upstream corrector {
        server  news.backend.corrector:8000;
    }

    upstream classifier {
        server  news.backend.classifier:8000;
    }

    ### === CORS ORIGINS ===
    map $http_origin $allow_origin {
        default "*";
        #"~^http://localhost(:[0-9]+)?$" $http_origin;
    }

    server {
        listen  80;

        ### === PROXY X-FORWARDED ===
        proxy_set_header    Host                $proxy_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-Proto   $scheme;
        proxy_set_header    X-Forwarded-Host    $host;
        proxy_set_header    X-Forwarded-Server  $server_name;
        proxy_set_header    X-Forwarded-Port    $server_port;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;

        location / {
            ### === CORS PARAMS ===
            add_header  'Access-Control-Allow-Origin'   $allow_origin   always;
            add_header  'Access-Control-Allow-Methods'  'GET, POST, OPTIONS, PUT, DELETE'   always;
            add_header  'Access-Control-Allow-Headers'  'Authorization,Content-Type,Accept,Origin,User-Agent,X-Requested-With'  always;
            add_header  'Access-Control-Max-Age'        1728000;

            ### === ROUTES ===
            location = /oauth2/auth {
                proxy_pass              http://news.backend.oauth2:4180;
                proxy_set_header        Content-Length "";
                proxy_pass_request_body off;
            }

            location /oauth2/ {
                proxy_pass      http://news.backend.oauth2:4180;
            }

            location /api/ {
                #auth_request     /oauth2/auth;
                #error_page 401 = /oauth2/sign_in?rd=$request_uri;

                proxy_pass      http://news.backend.server:8000;
            }

            location ~ ^/ai/(?<service>classifier|corrector)$ {
                set $service    $1;

                auth_request    /oauth2/auth;
                error_page 401 = /oauth2/sign_in?rd=$request_uri;
                
                proxy_pass      http://$service/query;
                proxy_read_timeout      300s;
                proxy_connect_timeout   300s;
                proxy_send_timeout      300s;
            }
        }

        access_log  /var/log/nginx/access.log;
        error_log   /var/log/nginx/error.log;
    }
}