volumes:
  persist-db:
  persist-server:    

networks:
  backend-net:
    driver: bridge

services:
  # === Server ===
  database:
    image: mysql:latest
    volumes:
      - persist-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_USER=${DB_SPRING_USER}
      - MYSQL_PASSWORD=${DB_SPRING_PASSWD}
      - MYSQL_DATABASE=news
    expose:
      - 3306
    networks:
      backend-net:
        aliases:
          - news.backend.db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  server:
    build: NewsAPI
    volumes:
      - persist-server:/home/spring/images
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://news.backend.db:3306/news
      - SPRING_DATASOURCE_USERNAME=${DB_SPRING_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_SPRING_PASSWD}
    expose:
      - 8000
    networks:
      backend-net:
        aliases:
          - news.backend.server
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      start_period: 15s
      interval: 10s
      timeout: 10s
      retries: 3

  # === AI ===
  classifier:
    build: NewsAI/Classifier
    environment:
      - HF_TOKEN=${CLASSIFIER_TOKEN}
      - HF_API=${CLASSIFIER_API}
    expose:
      - 8000
    networks:
      backend-net:
        aliases:
          - news.backend.classifier
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8000; echo -e 'GET /health HTTP/1.1\r\nHost: localhost:8000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q 'UP' && exit 0 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  corrector:
    build: NewsAI/Corrector
    environment:
      - HF_TOKEN=${CORRECTOR_TOKEN}
      - HF_API=${CORRECTOR_API}
      - HF_MODEL=${CORRECTOR_MODEL}
    expose:
      - 8000
    networks:
      backend-net:
        aliases:
          - news.backend.corrector
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8000; echo -e 'GET /health HTTP/1.1\r\nHost: localhost:8000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q 'UP' && exit 0 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  # === Authentication ===
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./NewsAuth/export:/opt/keycloak/data/import/:ro
    environment:
      # --- HTTP Configurations ---
      - KC_HTTP_ENABLED=true
      - KC_HTTP_HOST=0.0.0.0
      - KC_HTTP_PORT=8000
      # --- Proxy Configurations ---
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME_STRICT_HTTPS=false
      # --- Realm ---
      - KC_IMPORT=/opt/keycloak/data/import/
      # --- Logging and Metrics ---
      - KC_LOG_LEVEL=info
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command:
      - start-dev
      - --import-realm
    ports:
      - 8000:8000
    expose:
      - 8000
      - 9000
    networks:
      backend-net:
        aliases:
          - news.backend.keycloak
          - news-keycloak-alias.127.0.0.1.nip.io
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1"]
      start_period: 30s
      interval: 20s
      timeout: 20s
      retries: 3

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    volumes:
      - ./NewsAuth/oauth2-proxy.cfg:/oauth2-proxy.cfg
    depends_on:
      keycloak: { condition: service_healthy }
    command:
      - --config 
      - /oauth2-proxy.cfg
    expose: 
      - 4180
    networks:
      backend-net:
        aliases:
          - news.backend.oauth2

  # === Reverse proxy ===
  reverse_proxy:
    image: nginx:latest
    volumes:
      - ./NewsProxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    expose:
      - 80
    networks:
      backend-net:
        aliases:
          - news.backend
    depends_on:
      oauth2-proxy: { condition: service_started }
      server: { condition: service_healthy }
      #classifier: { condition: service_healthy }
      #corrector: { condition: service_healthy }

  # === Web app ===
  web-app:
    build:
      context: NewsWeb
      args:
        - SERVICE_DOMAIN=localhost:8080
    ports:
      - 80:80
    expose:
      - 80
    networks:
      backend-net:
        aliases:
          - news.frontend.web
    depends_on:
      reverse_proxy: { condition: service_started }