volumes:
  persist-db:
  persist-server:    

networks:
  backend-net:
    driver: bridge

services:
  # --- Server ---
  database:
    image: mysql:latest
    volumes:
      - persist-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_USER=${DB_SPRING_USER}
      - MYSQL_PASSWORD=${DB_SPRING_PASSWD}
      - MYSQL_DATABASE=news
    expose:
      - 3306
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  server:
    build: NewsAPI
    volumes:
      - persist-server:/home/spring/images
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/news
      - SPRING_DATASOURCE_USERNAME=${DB_SPRING_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_SPRING_PASSWD}
    expose:
      - 8081
    networks:
      - backend-net
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      start_period: 15s
      interval: 10s
      timeout: 10s
      retries: 3

  # --- AI ---
  classifier:
    build: NewsAI/Classifier
    environment:
      - HF_TOKEN=${CLASSIFIER_TOKEN}
      - HF_API=${CLASSIFIER_API}
    expose:
      - 8000
    networks:
      backend-net:
        aliases:
          - ai.classifier
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8000; echo -e 'GET /health HTTP/1.1\r\nHost: localhost:8000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q 'UP' && exit 0 || exit 1"]
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 3

  corrector:
    build: NewsAI/Corrector
    environment:
      - HF_TOKEN=${CORRECTOR_TOKEN}
      - HF_API=${CORRECTOR_API}
      - HF_MODEL=${CORRECTOR_MODEL}
    expose:
      - 8000
    networks:
      backend-net:
        aliases:
          - ai.corrector
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8000; echo -e 'GET /health HTTP/1.1\r\nHost: localhost:8000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q 'UP' && exit 0 || exit 1"]
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 3

  # === Authentication ===
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./NewsAuth/Keycloak/import:/opt/keycloak/data/import/:ro
    environment:
      # --- Proxy and Hostname Configuration ---
      #- KC_PROXY_HEDERS=xforwarded
      - KC_HOSTNAME=http://keycloak:8080
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true

      # --- Import Realms ---
      - KC_IMPORT=/opt/keycloak/data/import/

      # --- Logging and Metrics ---
      - KC_LOG_LEVEL=info
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=false
    command:
      - start-dev
      - --import-realm
    ports:
      - 1234:8080
    expose:
      - 8080
      - 9000
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command: --config /oauth2-proxy.cfg
    expose:
      - 4180
    volumes:
      - ./NewsAuth/OAuth2/oauth2-proxy.cfg:/oauth2-proxy.cfg
    depends_on:
      keycloak: { condition: service_healthy }
    networks:
      - backend-net

  # --- Reverse proxy ---
  reverse_proxy:
    image: nginx:latest
    volumes:
      - ./NewsProxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    expose:
      - 80
    networks:
      - backend-net
    depends_on:
      oauth2-proxy: { condition: service_started }
      server: { condition: service_healthy }
      #classifier: { condition: service_healthy }
      #corrector: { condition: service_healthy }